-- ============================================================
-- ARCADA — Clean Wipe + Full Reseed
-- Fixes: duplicate products, missing images, variant SKU conflicts
-- Run this ONCE in the Supabase SQL Editor to get a clean slate.
-- Replace YOUR_PROJECT_REF with your actual Supabase project ref:
--   cffrahhkwvvlvdkpivxc
-- ============================================================

-- ── 0. COLUMN SAFETY ─────────────────────────────────────────
ALTER TABLE products ADD COLUMN IF NOT EXISTS base_price    numeric(10,2) NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS images        text[]        NOT NULL DEFAULT '{}';
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_active     boolean       NOT NULL DEFAULT true;
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_featured   boolean       NOT NULL DEFAULT false;
ALTER TABLE products ADD COLUMN IF NOT EXISTS description_en text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS description_fr text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS description_ar text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS updated_at    timestamptz   DEFAULT now();
ALTER TABLE categories ADD COLUMN IF NOT EXISTS description_en text;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS description_fr text;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS description_ar text;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS image_url      text;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS sort_order     int DEFAULT 0;
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS name_en        text;
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS name_fr        text;
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS name_ar        text;
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS sku            text;
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS price_modifier  numeric(10,2) DEFAULT 0;
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS stock          int DEFAULT 0;
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS color_hex      text;

-- ── 1. WIPE EVERYTHING ───────────────────────────────────────
DELETE FROM order_items;
DELETE FROM orders;
DELETE FROM product_variants;
DELETE FROM products;
DELETE FROM categories;

-- ── 2. CATEGORIES ────────────────────────────────────────────
INSERT INTO categories (slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, sort_order) VALUES
('silos',   'Silos Collection',   'Collection Silos',   'مجموعة سيلوس',   'Elongated picket-shaped ceramic tiles (10x30 cm) with artisanal glazed finishes.',        'Carreaux en forme de piquet allongé (10x30 cm) avec des finitions émaillées artisanales.',        'بلاط سيراميك بشكل لقطة مستطيلة (10×30 سم) بتشطيبات مزججة حرفية.',        1),
('atelier', 'Atelier Collection', 'Collection Atelier', 'مجموعة أتيليه',  'Artisan-crafted leaf-shaped tiles (10x30 cm) with embossed relief and metallic finishes.', 'Carreaux en forme de feuille (10x30 cm) avec textures en relief et finitions métalliques.', 'بلاط على شكل ورقة (10×30 سم) بنقوش بارزة وتشطيبات معدنية.',              2),
('ducal',   'Ducal Collection',   'Collection Ducal',   'مجموعة دوكال',   'Classic subway-style rectangular tiles (10x30 cm) with an aged handmade look.',           'Carreaux rectangulaires de style métro (10x30 cm) avec un aspect vieilli fait main.',      'بلاط مستطيل بأسلوب المترو (10×30 سم) بمظهر عتيق مصنوع يدويًا.',           3),
('leaf',    'Leaf Collection',    'Collection Leaf',    'مجموعة ليف',     'Leaf-shaped tiles (15x30 cm) in vibrant glazed and metallic finishes.',                    'Carreaux en forme de feuille (15x30 cm) aux finitions émaillées et métalliques vibrantes.','بلاط على شكل ورقة (15×30 سم) بتشطيبات مزججة ومعدنية زاهية.',              4),
('gonos',   'Gonos Collection',   'Collection Gonos',   'مجموعة غونوس',   'Elongated hexagonal tiles (15x30 cm) with playful decorative motifs.',                    'Carreaux hexagonaux allongés (15x30 cm) avec des motifs décoratifs ludiques.',             'بلاط سداسي مستطيل (15×30 سم) بزخارف مرحة.',                               5),
('chic',    'Chic Collection',    'Collection Chic',    'مجموعة شيك',     'Moroccan-inspired scallop and arabesque tiles (20x20 cm) in bold glazed and metallic finishes.','Carreaux en écaille et arabesque d''inspiration marocaine (20x20 cm).',          'بلاط صدفي وأرابيسك مستوحى من المغرب (20×20 سم).',                          6),
('kronfel', 'Kronfel Collection', 'Collection Kronfel', 'مجموعة كرونفل',  'Traditional hand-painted square tiles (20x20 cm) with rich ornamental patterns.',         'Carreaux carrés peints à la main (20x20 cm) avec riches motifs ornementaux.',              'بلاط مربع مطلي يدويًا (20×20 سم) بزخارف زخرفية غنية.',                   7),
('casbah',  'Casbah Collection',  'Collection Casbah',  'مجموعة قصبة',    'Andalusian-style hand-painted tiles (20x20 cm) with botanical motifs.',                   'Carreaux peints à la main de style andalou (20x20 cm) avec motifs botaniques.',            'بلاط بالأسلوب الأندلسي مرسوم يدويًا (20×20 سم) بزخارف نباتية.',           8),
('yasmine', 'Yasmine Collection', 'Collection Yasmine', 'مجموعة ياسمين',  'Ottoman-inspired hand-painted tiles (20x20 cm) with intricate floral arabesque.',         'Carreaux peints à la main d''inspiration ottomane (20x20 cm) avec arabesque florale.',     'بلاط مستوحى من العثمانية مرسوم يدويًا (20×20 سم) بأرابيسك زهري.',         9);

-- ── 3. PRODUCTS (with full image URLs baked in) ──────────────
-- Storage base: https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/

-- SILOS
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'silos-terracota', 'Silos Terracota', 'Silos Terracota', 'سيلوس تيراكوتا', 'Warm terracotta-toned picket tile with a rich earthy glaze. 10x30 cm, 3 faces.', 'Carreau piquet aux tons terracotta chauds avec une glaçure riche. 10x30 cm, 3 faces.', 'بلاط لقطة بدرجات تيراكوتا دافئة بطلاء غني. 10×30 سم، 3 وجوه.', 0.00, true, true,  ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-SIL-001.jpg'] FROM categories c WHERE c.slug = 'silos';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'silos-beige', 'Silos Beige', 'Silos Beige', 'سيلوس بيج', 'Soft beige picket tile with a delicate antique glaze. 10x30 cm, 3 faces.', 'Carreau piquet beige doux avec une glaçure antique délicate. 10x30 cm, 3 faces.', 'بلاط لقطة بيج ناعم بطلاء عتيق رقيق. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-SIL-002.jpg'] FROM categories c WHERE c.slug = 'silos';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'silos-dec-natura-beige', 'Silos Dec Natura Beige', 'Silos Dec Natura Beige', 'سيلوس ديك ناتورا بيج', 'Beige picket tile with a hand-painted tropical leaf décor. 10x30 cm, 3 faces.', 'Carreau piquet beige avec un décor de feuilles tropicales peint à la main. 10x30 cm.', 'بلاط لقطة بيج بزخرفة أوراق استوائية مرسومة يدويًا. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-SIL-003.jpg'] FROM categories c WHERE c.slug = 'silos';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'silos-dec-jamaica-beige', 'Silos Dec Jamaica Beige', 'Silos Dec Jamaica Beige', 'سيلوس ديك جامايكا بيج', 'Beige picket tile with a vibrant hibiscus and tropical leaf décor. 10x30 cm.', 'Carreau piquet beige avec un décor hibiscus et feuilles tropicales. 10x30 cm.', 'بلاط لقطة بيج بزخرفة الكركديه والأوراق الاستوائية. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-SIL-004.jpg'] FROM categories c WHERE c.slug = 'silos';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'silos-dec-celestina-beige', 'Silos Dec Celestina Beige', 'Silos Dec Celestina Beige', 'سيلوس ديك سيليستينا بيج', 'Beige picket tile with an elegant bird and floral branch décor. 10x30 cm.', 'Carreau piquet beige avec un décor oiseaux et branches fleuries. 10x30 cm.', 'بلاط لقطة بيج بزخرفة الطيور والأغصان المزهرة. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-SIL-005.jpg'] FROM categories c WHERE c.slug = 'silos';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'silos-antracita', 'Silos Antracita', 'Silos Antracita', 'سيلوس أنتراسيتا', 'Deep anthracite-toned picket tile with a textured matte glaze. 10x30 cm, 3 faces.', 'Carreau piquet anthracite avec glaçure mate texturée. 10x30 cm.', 'بلاط لقطة أنثراسيت داكنة بطلاء مطفي منسوج. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-SIL-006.jpg'] FROM categories c WHERE c.slug = 'silos';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'silos-gris', 'Silos Gris', 'Silos Gris', 'سيلوس رمادي', 'Light grey picket tile with a subtle textured glaze. 10x30 cm, 3 faces.', 'Carreau piquet gris clair avec glaçure texturée subtile. 10x30 cm.', 'بلاط لقطة رمادي فاتح بطلاء منسوج خفيف. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-SIL-007.jpg'] FROM categories c WHERE c.slug = 'silos';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'silos-dec-natura-gris', 'Silos Dec Natura Gris', 'Silos Dec Natura Gris', 'سيلوس ديك ناتورا رمادي', 'Grey picket tile with a hand-painted tropical leaf décor. 10x30 cm.', 'Carreau piquet gris avec décor feuilles tropicales peint à la main. 10x30 cm.', 'بلاط لقطة رمادي بزخرفة أوراق استوائية مرسومة يدويًا. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-SIL-008.jpg'] FROM categories c WHERE c.slug = 'silos';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'silos-dec-jamaica-gris', 'Silos Dec Jamaica Gris', 'Silos Dec Jamaica Gris', 'سيلوس ديك جامايكا رمادي', 'Grey picket tile with a hibiscus and tropical leaf décor. 10x30 cm.', 'Carreau piquet gris avec décor hibiscus et feuilles tropicales. 10x30 cm.', 'بلاط لقطة رمادي بزخرفة الكركديه والأوراق الاستوائية. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-SIL-009.jpg'] FROM categories c WHERE c.slug = 'silos';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'silos-dec-celestina-gris', 'Silos Dec Celestina Gris', 'Silos Dec Celestina Gris', 'سيلوس ديك سيليستينا رمادي', 'Grey picket tile with a bird and floral branch décor. 10x30 cm.', 'Carreau piquet gris avec décor oiseaux et branches fleuries. 10x30 cm.', 'بلاط لقطة رمادي بزخرفة الطيور والأغصان المزهرة. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-SIL-010.jpg'] FROM categories c WHERE c.slug = 'silos';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'silos-dec-gold', 'Silos Dec Gold', 'Silos Dec Gold', 'سيلوس ديك ذهبي', 'Luxurious gold-finish picket tile with ornate embossed relief. 10x30 cm, 5 faces.', 'Carreau piquet finition or luxueux avec motifs en relief ornementaux. 10x30 cm, 5 faces.', 'بلاط لقطة فاخر بتشطيب ذهبي مع نقوش بارزة زخرفية. 10×30 سم، 5 وجوه.', 0.00, true, true,  ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-SIL-011.jpg'] FROM categories c WHERE c.slug = 'silos';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'silos-dec-beige', 'Silos Dec Beige', 'Silos Dec Beige', 'سيلوس ديك بيج', 'Beige picket tile with intricate floral embossed patterns. 10x30 cm, 5 faces.', 'Carreau piquet beige avec motifs floraux en relief complexes. 10x30 cm, 5 faces.', 'بلاط لقطة بيج بنقوش زهرية بارزة معقدة. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-SIL-012.jpg'] FROM categories c WHERE c.slug = 'silos';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'silos-dec-mix-beige', 'Silos Dec Mix Beige', 'Silos Dec Mix Beige', 'سيلوس ديك ميكس بيج', 'Mixed beige decorative picket tile. 10x30 cm.', 'Carreau piquet décoratif beige mélangé. 10x30 cm.', 'بلاط لقطة بيج مزدوج. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-SIL-013.jpg'] FROM categories c WHERE c.slug = 'silos';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'silos-dec-silver', 'Silos Dec Silver', 'Silos Dec Silver', 'سيلوس ديك فضي', 'Premium silver-finish picket tile with ornate embossed relief. 10x30 cm, 5 faces.', 'Carreau piquet finition argent premium avec relief ornemental. 10x30 cm, 5 faces.', 'بلاط لقطة فضي فاخر بنقوش بارزة زخرفية. 10×30 سم.', 0.00, true, true,  ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-SIL-014.jpg'] FROM categories c WHERE c.slug = 'silos';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'silos-dec-gris', 'Silos Dec Gris', 'Silos Dec Gris', 'سيلوس ديك رمادي', 'Grey picket tile with ornate embossed floral patterns. 10x30 cm, 5 faces.', 'Carreau piquet gris avec motifs floraux en relief ornementaux. 10x30 cm, 5 faces.', 'بلاط لقطة رمادي بنقوش زهرية بارزة زخرفية. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-SIL-015.jpg'] FROM categories c WHERE c.slug = 'silos';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'silos-dec-mix-gris', 'Silos Dec Mix Gris', 'Silos Dec Mix Gris', 'سيلوس ديك ميكس رمادي', 'Mixed grey decorative picket tile. 10x30 cm.', 'Carreau piquet décoratif gris mélangé. 10x30 cm.', 'بلاط لقطة رمادي مزدوج. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-SIL-016.jpg'] FROM categories c WHERE c.slug = 'silos';

-- ATELIER
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'atelier-r1-pb-miel', 'Atelier R1 Pb Miel', 'Atelier R1 Pb Miel', 'أتيليه R1 Pb عسلي', 'Honey-toned embossed leaf tile with a rich polished body finish. 10x30 cm.', 'Carreau feuille gaufré couleur miel avec finition corps poli riche. 10x30 cm.', 'بلاط ورقة منقوش بدرجة عسلية بتشطيب جسم مصقول غني. 10×30 سم.', 0.00, true, true,  ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-ATL-001.jpg'] FROM categories c WHERE c.slug = 'atelier';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'atelier-r1-ec-blanc', 'Atelier R1 EC Blanc', 'Atelier R1 EC Blanc', 'أتيليه R1 EC أبيض', 'Crisp white embossed leaf tile with an extra-clear glaze. 10x30 cm.', 'Carreau feuille gaufré blanc pur avec glaçure extra-claire. 10x30 cm.', 'بلاط ورقة منقوش أبيض نقي بطلاء شفاف فائق. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-ATL-002.jpg'] FROM categories c WHERE c.slug = 'atelier';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'atelier-r1-pb-vert', 'Atelier R1 Pb Vert', 'Atelier R1 Pb Vert', 'أتيليه R1 Pb أخضر', 'Deep forest-green embossed leaf tile with a glossy polished finish. 10x30 cm.', 'Carreau feuille gaufré vert forêt avec finition brillante polie. 10x30 cm.', 'بلاط ورقة منقوش باللون الأخضر الغابي بتشطيب لامع مصقول. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-ATL-003.jpg'] FROM categories c WHERE c.slug = 'atelier';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'atelier-r1-pb-bleu', 'Atelier R1 Pb Bleu', 'Atelier R1 Pb Bleu', 'أتيليه R1 Pb أزرق', 'Bold cobalt-blue embossed leaf tile with a polished body finish. 10x30 cm.', 'Carreau feuille gaufré bleu cobalt avec finition corps poli. 10x30 cm.', 'بلاط ورقة منقوش باللون الأزرق الكوبالت بتشطيب جسم مصقول. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-ATL-004.jpg'] FROM categories c WHERE c.slug = 'atelier';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'atelier-r1-mtl-gold', 'Atelier R1 Mtl Gold', 'Atelier R1 Mtl Gold', 'أتيليه R1 معدني ذهبي', 'Striking metallic gold leaf tile with an ultra-glossy electro-plated finish. 10x30 cm.', 'Carreau feuille métallique or avec finition électrodéposée ultra-brillante. 10x30 cm.', 'بلاط ورقة معدني ذهبي مذهل بتشطيب كهروكيميائي فائق اللمعان. 10×30 سم.', 0.00, true, true,  ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-ATL-005.jpg'] FROM categories c WHERE c.slug = 'atelier';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'atelier-r1-mtl-rose-gold', 'Atelier R1 Mtl Rose Gold', 'Atelier R1 Mtl Rose Gold', 'أتيليه R1 معدني روز غولد', 'Elegant rose-gold metallic leaf tile. 10x30 cm.', 'Élégant carreau feuille métallique rose gold. 10x30 cm.', 'بلاط ورقة معدني روز غولد أنيق. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-ATL-006.jpg'] FROM categories c WHERE c.slug = 'atelier';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'atelier-r1-mtl-silver', 'Atelier R1 Mtl Silver', 'Atelier R1 Mtl Silver', 'أتيليه R1 معدني فضي', 'Sleek metallic silver leaf tile with a mirror-like electroplated finish. 10x30 cm.', 'Carreau feuille métallique argent élégant avec finition miroir. 10x30 cm.', 'بلاط ورقة معدني فضي أنيق بتشطيب مرآة كهروكيميائية. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-ATL-007.jpg'] FROM categories c WHERE c.slug = 'atelier';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'atelier-r1-mtl-bleu-petrole', 'Atelier R1 Mtl Bleu Pétrole', 'Atelier R1 Mtl Bleu Pétrole', 'أتيليه R1 معدني أزرق بترولي', 'Deep teal petroleum-blue metallic leaf tile. 10x30 cm.', 'Carreau feuille métallique bleu pétrole profond. 10x30 cm.', 'بلاط ورقة معدني أزرق بترولي داكن. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-ATL-008.jpg'] FROM categories c WHERE c.slug = 'atelier';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'atelier-r1-ird-rose', 'Atelier R1 Ird Rose', 'Atelier R1 Ird Rose', 'أتيليه R1 Ird وردي', 'Soft pink iridescent leaf tile with a satin glaze. 10x30 cm.', 'Carreau feuille irisé rose doux avec glaçure satinée. 10x30 cm.', 'بلاط ورقة وردي متقزح بطلاء ساتان. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-ATL-009.jpg'] FROM categories c WHERE c.slug = 'atelier';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'atelier-r1-ird-bleu', 'Atelier R1 Ird Bleu', 'Atelier R1 Ird Bleu', 'أتيليه R1 Ird أزرق', 'Vibrant teal iridescent leaf tile. 10x30 cm.', 'Carreau feuille irisé sarcelle vibrant. 10x30 cm.', 'بلاط ورقة أزرق متقزح زاهٍ. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-ATL-010.jpg'] FROM categories c WHERE c.slug = 'atelier';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'atelier-dec-floral-3', 'Atelier Dec Floral 3', 'Atelier Dec Floral 3', 'أتيليه ديك فلورال 3', 'Picket tile with an orange and red floral bouquet décor. 10x30 cm, 6 faces.', 'Carreau piquet avec décor bouquet floral orange et rouge. 10x30 cm, 6 faces.', 'بلاط لقطة بزخرفة باقة أزهار برتقالية وحمراء. 10×30 سم، 6 وجوه.', 0.00, true, true,  ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-ATL-011.jpg'] FROM categories c WHERE c.slug = 'atelier';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'atelier-dec-floral-4', 'Atelier Dec Floral 4', 'Atelier Dec Floral 4', 'أتيليه ديك فلورال 4', 'Picket tile with a yellow and blue wildflower décor. 10x30 cm, 6 faces.', 'Carreau piquet avec décor fleurs sauvages jaunes et bleues. 10x30 cm, 6 faces.', 'بلاط لقطة بزخرفة أزهار برية صفراء وزرقاء. 10×30 سم، 6 وجوه.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-ATL-012.jpg'] FROM categories c WHERE c.slug = 'atelier';

-- DUCAL
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'ducal-terracota', 'Ducal Terracota', 'Ducal Terracota', 'دوكال تيراكوتا', 'Handmade-look terracotta subway tile. 10x30 cm, 3 faces.', 'Carreau métro terracotta à aspect fait main. 10x30 cm, 3 faces.', 'بلاط مترو تيراكوتا بمظهر مصنوع يدويًا. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-DUC-001.jpg'] FROM categories c WHERE c.slug = 'ducal';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'ducal-beige', 'Ducal Beige', 'Ducal Beige', 'دوكال بيج', 'Classic beige subway tile with a linen-white handmade glaze. 10x30 cm.', 'Carreau métro beige classique avec glaçure blanc-lin fait main. 10x30 cm.', 'بلاط مترو بيج كلاسيكي بطلاء أبيض كتاني مصنوع يدويًا. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-DUC-002.jpg'] FROM categories c WHERE c.slug = 'ducal';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'ducal-dec-tucan', 'Ducal Dec Tucan', 'Ducal Dec Tucan', 'دوكال ديك توكان', 'Subway tile with a vibrant toucan and tropical foliage décor. 10x30 cm, 3 faces.', 'Carreau métro avec décor toucan et feuillage tropical. 10x30 cm, 3 faces.', 'بلاط مترو بزخرفة طيور التوكان والأوراق الاستوائية. 10×30 سم.', 0.00, true, true,  ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-DUC-003.jpg'] FROM categories c WHERE c.slug = 'ducal';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'ducal-dec-jamaica', 'Ducal Dec Jamaica', 'Ducal Dec Jamaica', 'دوكال ديك جامايكا', 'Subway tile with a hibiscus flower and tropical leaf décor. 10x30 cm.', 'Carreau métro avec décor fleur d''hibiscus et feuilles tropicales. 10x30 cm.', 'بلاط مترو بزخرفة زهرة الكركديه والأوراق الاستوائية. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-DUC-004.jpg'] FROM categories c WHERE c.slug = 'ducal';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'ducal-antracita', 'Ducal Antracita', 'Ducal Antracita', 'دوكال أنتراسيتا', 'Anthracite grey handmade-look subway tile. 10x30 cm, 3 faces.', 'Carreau métro anthracite à aspect fait main. 10x30 cm, 3 faces.', 'بلاط مترو رمادي أنثراسيت بمظهر مصنوع يدويًا. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-DUC-005.jpg'] FROM categories c WHERE c.slug = 'ducal';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'ducal-gris', 'Ducal Gris', 'Ducal Gris', 'دوكال رمادي', 'Light grey handmade-look subway tile. 10x30 cm, 3 faces.', 'Carreau métro gris clair à aspect fait main. 10x30 cm, 3 faces.', 'بلاط مترو رمادي فاتح بمظهر مصنوع يدويًا. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-DUC-006.jpg'] FROM categories c WHERE c.slug = 'ducal';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'ducal-dec-celestina', 'Ducal Dec Celestina', 'Ducal Dec Celestina', 'دوكال ديك سيليستينا', 'Subway tile with delicate blue floral and leaf branch décor. 10x30 cm.', 'Carreau métro avec décor floral bleu et branches de feuilles. 10x30 cm.', 'بلاط مترو بزخرفة أزهار زرقاء رقيقة وأغصان أوراق. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-DUC-007.jpg'] FROM categories c WHERE c.slug = 'ducal';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'ducal-dec-gold', 'Ducal Dec Gold', 'Ducal Dec Gold', 'دوكال ديك ذهبي', 'Subway tile with a rich gold metallic floral décor. 10x30 cm.', 'Carreau métro avec riche décor floral métallique or. 10x30 cm.', 'بلاط مترو بزخرفة زهرية معدنية ذهبية غنية. 10×30 سم.', 0.00, true, true,  ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-DUC-008.jpg'] FROM categories c WHERE c.slug = 'ducal';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'ducal-dec-beige-decor', 'Ducal Dec Beige', 'Ducal Dec Beige', 'دوكال ديك بيج', 'Subway tile with a beige ornamental patchwork décor. 10x30 cm.', 'Carreau métro avec décor patchwork ornemental beige. 10x30 cm.', 'بلاط مترو بزخرفة رقعية زخرفية بيج. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-DUC-009.jpg'] FROM categories c WHERE c.slug = 'ducal';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'ducal-dec-silver', 'Ducal Dec Silver', 'Ducal Dec Silver', 'دوكال ديك فضي', 'Subway tile with a silver metallic ornamental décor. 10x30 cm.', 'Carreau métro avec décor ornemental métallique argent. 10x30 cm.', 'بلاط مترو بزخرفة زخرفية معدنية فضية. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-DUC-010.jpg'] FROM categories c WHERE c.slug = 'ducal';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'ducal-dec-gris-decor', 'Ducal Dec Gris', 'Ducal Dec Gris', 'دوكال ديك رمادي', 'Subway tile with a grey ornamental patchwork décor. 10x30 cm.', 'Carreau métro avec décor patchwork ornemental gris. 10x30 cm.', 'بلاط مترو بزخرفة رقعية زخرفية رمادية. 10×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-DUC-011.jpg'] FROM categories c WHERE c.slug = 'ducal';

-- LEAF
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'leaf-r1-pb-bleu', 'Leaf R1 Pb Bleu', 'Leaf R1 Pb Bleu', 'ليف R1 Pb أزرق', 'Striking cobalt-blue leaf-shaped tile with a glossy polished body. 15x30 cm.', 'Carreau en forme de feuille bleu cobalt avec corps poli brillant. 15x30 cm.', 'بلاط على شكل ورقة أزرق كوبالت مذهل بجسم مصقول لامع. 15×30 سم.', 0.00, true, true,  ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-LEA-001.jpg'] FROM categories c WHERE c.slug = 'leaf';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'leaf-r1-pb-miel', 'Leaf R1 Pb Miel', 'Leaf R1 Pb Miel', 'ليف R1 Pb عسلي', 'Warm honey-orange leaf tile with a rich polished finish. 15x30 cm.', 'Carreau feuille miel-orange avec finition polie riche. 15x30 cm.', 'بلاط ورقة عسلي برتقالي دافئ بتشطيب مصقول غني. 15×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-LEA-002.jpg'] FROM categories c WHERE c.slug = 'leaf';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'leaf-r1-pb-vert', 'Leaf R1 Pb Vert', 'Leaf R1 Pb Vert', 'ليف R1 Pb أخضر', 'Deep forest-green leaf tile with a polished body finish. 15x30 cm.', 'Carreau feuille vert forêt avec finition corps poli. 15x30 cm.', 'بلاط ورقة أخضر غابي بتشطيب جسم مصقول. 15×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-LEA-003.jpg'] FROM categories c WHERE c.slug = 'leaf';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'leaf-r1-ec-blanc', 'Leaf R1 EC Blanc', 'Leaf R1 EC Blanc', 'ليف R1 EC أبيض', 'Pure white embossed leaf tile with extra-clear glaze. 15x30 cm.', 'Carreau feuille blanc pur gaufré avec glaçure extra-claire. 15x30 cm.', 'بلاط ورقة منقوش أبيض نقي بطلاء شفاف فائق. 15×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-LEA-004.jpg'] FROM categories c WHERE c.slug = 'leaf';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'leaf-r1-mtl-rose-gold', 'Leaf R1 Mtl Rose Gold', 'Leaf R1 Mtl Rose Gold', 'ليف R1 معدني روز غولد', 'Elegant rose-gold metallic leaf tile. 15x30 cm.', 'Élégant carreau feuille métallique rose gold. 15x30 cm.', 'بلاط ورقة معدني روز غولد أنيق. 15×30 سم.', 0.00, true, true,  ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-LEA-005.jpg'] FROM categories c WHERE c.slug = 'leaf';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'leaf-r1-mtl-mauve', 'Leaf R1 Mtl Mauve', 'Leaf R1 Mtl Mauve', 'ليف R1 معدني موف', 'Deep mauve/purple metallic leaf tile. 15x30 cm.', 'Carreau feuille métallique mauve/violet. 15x30 cm.', 'بلاط ورقة معدني موف/بنفسجي. 15×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-LEA-006.jpg'] FROM categories c WHERE c.slug = 'leaf';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'leaf-r1-mtl-bleu-petrole', 'Leaf R1 Mtl Bleu Pétrole', 'Leaf R1 Mtl Bleu Pétrole', 'ليف R1 معدني أزرق بترولي', 'Teal petroleum-blue metallic leaf tile. 15x30 cm.', 'Carreau feuille métallique bleu pétrole. 15x30 cm.', 'بلاط ورقة معدني أزرق بترولي. 15×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-LEA-007.jpg'] FROM categories c WHERE c.slug = 'leaf';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'leaf-dec-floral-1', 'Leaf Dec Floral 1', 'Leaf Dec Floral 1', 'ليف ديك فلورال 1', 'Leaf-shaped tile with watercolour botanical print in green and orange tones. 15x30 cm, 6 faces.', 'Carreau feuille avec impression botanique aquarelle en tons verts et orangés. 15x30 cm, 6 faces.', 'بلاط على شكل ورقة بطباعة نباتية مائية. 15×30 سم، 6 وجوه.', 0.00, true, true,  ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-LEA-008.jpg'] FROM categories c WHERE c.slug = 'leaf';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'leaf-dec-floral-2', 'Leaf Dec Floral 2', 'Leaf Dec Floral 2', 'ليف ديك فلورال 2', 'Leaf-shaped tile with a multi-coloured wildflower print. 15x30 cm, 6 faces.', 'Carreau feuille avec impression fleurs sauvages multicolores. 15x30 cm, 6 faces.', 'بلاط على شكل ورقة بطباعة أزهار برية متعددة الألوان. 15×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-LEA-009.jpg'] FROM categories c WHERE c.slug = 'leaf';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'leaf-dec-floral-3', 'Leaf Dec Floral 3', 'Leaf Dec Floral 3', 'ليف ديك فلورال 3', 'Leaf-shaped tile with red and yellow floral bouquet print. 15x30 cm, 6 faces.', 'Carreau feuille avec impression bouquet floral rouge et jaune. 15x30 cm, 6 faces.', 'بلاط على شكل ورقة بطباعة باقة أزهار حمراء وصفراء. 15×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-LEA-010.jpg'] FROM categories c WHERE c.slug = 'leaf';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'leaf-dec-floral-4', 'Leaf Dec Floral 4', 'Leaf Dec Floral 4', 'ليف ديك فلورال 4', 'Leaf-shaped tile with blue and yellow wildflower print. 15x30 cm, 6 faces.', 'Carreau feuille avec impression fleurs sauvages bleues et jaunes. 15x30 cm, 6 faces.', 'بلاط على شكل ورقة بطباعة أزهار برية زرقاء وصفراء. 15×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-LEA-011.jpg'] FROM categories c WHERE c.slug = 'leaf';

-- GONOS
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'gonos-dec-girl', 'Gonos Dec Girl', 'Gonos Dec Girl', 'غونوس ديك بنت', 'Elongated hexagonal tile with a colourful children''s girl motif décor. 15x30 cm, 5 faces.', 'Carreau hexagonal allongé avec décor motif enfant fille coloré. 15x30 cm, 5 faces.', 'بلاط سداسي مستطيل بزخرفة ملونة بموضوع أطفال (بنت). 15×30 سم.', 0.00, true, true,  ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-GON-001.jpg'] FROM categories c WHERE c.slug = 'gonos';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'gonos-blanc', 'Gonos Blanc', 'Gonos Blanc', 'غونوس أبيض', 'Clean white elongated hexagonal tile with a matte finish. 15x30 cm.', 'Carreau hexagonal allongé blanc épuré avec finition mate. 15x30 cm.', 'بلاط سداسي مستطيل أبيض نظيف بتشطيب مطفي. 15×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-GON-002.jpg'] FROM categories c WHERE c.slug = 'gonos';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'gonos-dec-boy', 'Gonos Dec Boy', 'Gonos Dec Boy', 'غونوس ديك ولد', 'Elongated hexagonal tile with a colourful children''s boy motif décor. 15x30 cm, 5 faces.', 'Carreau hexagonal allongé avec décor motif enfant garçon coloré. 15x30 cm.', 'بلاط سداسي مستطيل بزخرفة ملونة بموضوع أطفال (ولد). 15×30 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-GON-003.jpg'] FROM categories c WHERE c.slug = 'gonos';

-- CHIC
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'chic-r1-pb-bleu', 'Chic R1 Pb Bleu', 'Chic R1 Pb Bleu', 'شيك R1 Pb أزرق', 'Bold cobalt-blue Moroccan scallop tile with embossed fan relief. 20x20 cm.', 'Carreau marocain en écaille cobalt avec relief ventail. 20x20 cm.', 'بلاط مغربي صدفي كوبالت جريء بنقش مروحي بارز. 20×20 سم.', 0.00, true, true,  ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-CHI-001.jpg'] FROM categories c WHERE c.slug = 'chic';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'chic-r1-pb-miel', 'Chic R1 Pb Miel', 'Chic R1 Pb Miel', 'شيك R1 Pb عسلي', 'Warm honey/amber scallop tile with embossed fan relief. 20x20 cm.', 'Carreau en écaille miel/ambre avec relief ventail. 20x20 cm.', 'بلاط صدفي عسلي/كهرماني دافئ بنقش مروحي بارز. 20×20 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-CHI-002.jpg'] FROM categories c WHERE c.slug = 'chic';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'chic-r1-pb-vert', 'Chic R1 Pb Vert', 'Chic R1 Pb Vert', 'شيك R1 Pb أخضر', 'Forest-green scallop tile with embossed fan relief. 20x20 cm.', 'Carreau en écaille vert forêt avec relief ventail. 20x20 cm.', 'بلاط صدفي أخضر غابي بنقش مروحي بارز. 20×20 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-CHI-003.jpg'] FROM categories c WHERE c.slug = 'chic';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'chic-r1-ec-blanc', 'Chic R1 EC Blanc', 'Chic R1 EC Blanc', 'شيك R1 EC أبيض', 'Pure white scallop tile with extra-clear glaze. 20x20 cm.', 'Carreau en écaille blanc pur avec glaçure extra-claire. 20x20 cm.', 'بلاط صدفي أبيض نقي بطلاء شفاف فائق. 20×20 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-CHI-004.jpg'] FROM categories c WHERE c.slug = 'chic';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'chic-r2-pb-bleu', 'Chic R2 Pb Bleu', 'Chic R2 Pb Bleu', 'شيك R2 Pb أزرق', 'Moroccan arabesque tile with ornate floral relief in cobalt blue. 20x20 cm.', 'Carreau arabesque marocain avec relief floral ornemental en bleu cobalt. 20x20 cm.', 'بلاط أرابيسك مغربي بنقش زهري زخرفي باللون الأزرق الكوبالت. 20×20 سم.', 0.00, true, true,  ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-CHI-005.jpg'] FROM categories c WHERE c.slug = 'chic';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'chic-r2-pb-miel', 'Chic R2 Pb Miel', 'Chic R2 Pb Miel', 'شيك R2 Pb عسلي', 'Moroccan arabesque tile with ornate floral relief in honey amber. 20x20 cm.', 'Carreau arabesque marocain avec relief floral en ambre miel. 20x20 cm.', 'بلاط أرابيسك مغربي بنقش زهري زخرفي بالعسلي الكهرماني. 20×20 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-CHI-006.jpg'] FROM categories c WHERE c.slug = 'chic';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'chic-r2-pb-vert', 'Chic R2 Pb Vert', 'Chic R2 Pb Vert', 'شيك R2 Pb أخضر', 'Moroccan arabesque tile with ornate floral relief in forest green. 20x20 cm.', 'Carreau arabesque marocain avec relief floral en vert forêt. 20x20 cm.', 'بلاط أرابيسك مغربي بنقش زهري زخرفي بالأخضر الغابي. 20×20 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-CHI-007.jpg'] FROM categories c WHERE c.slug = 'chic';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'chic-r2-ec-blanc', 'Chic R2 EC Blanc', 'Chic R2 EC Blanc', 'شيك R2 EC أبيض', 'White Moroccan arabesque tile with ornate floral embossed relief. 20x20 cm.', 'Carreau arabesque marocain blanc avec relief ornemental floral. 20x20 cm.', 'بلاط أرابيسك مغربي أبيض بنقش زهري زخرفي بارز. 20×20 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-CHI-008.jpg'] FROM categories c WHERE c.slug = 'chic';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'chic-r2-mtl-bleu-cobalte', 'Chic R2 Mtl Bleu Cobalte', 'Chic R2 Mtl Bleu Cobalte', 'شيك R2 معدني أزرق كوبالت', 'Arabesque tile with a brilliant cobalt-blue metallic electroplated finish. 20x20 cm.', 'Carreau arabesque avec finition métallique électrodéposée bleu cobalt. 20x20 cm.', 'بلاط أرابيسك بتشطيب معدني كهروكيميائي أزرق كوبالت لامع. 20×20 سم.', 0.00, true, true,  ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-CHI-009.jpg'] FROM categories c WHERE c.slug = 'chic';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'chic-r2-mtl-mauve', 'Chic R2 Mtl Mauve', 'Chic R2 Mtl Mauve', 'شيك R2 معدني موف', 'Arabesque tile with a vibrant mauve/fuchsia metallic finish. 20x20 cm.', 'Carreau arabesque avec finition métallique mauve/fuchsia. 20x20 cm.', 'بلاط أرابيسك بتشطيب معدني موف/فوشيا زاهٍ. 20×20 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-CHI-010.jpg'] FROM categories c WHERE c.slug = 'chic';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'chic-r2-mtl-gold', 'Chic R2 Mtl Gold', 'Chic R2 Mtl Gold', 'شيك R2 معدني ذهبي', 'Luxurious gold arabesque tile with an opulent metallic finish. 20x20 cm.', 'Carreau arabesque or luxueux avec finition métallique opulente. 20x20 cm.', 'بلاط أرابيسك ذهبي فاخر بتشطيب معدني بذيخ. 20×20 سم.', 0.00, true, true,  ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-CHI-011.jpg'] FROM categories c WHERE c.slug = 'chic';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'chic-r2-mtl-rose-gold', 'Chic R2 Mtl Rose Gold', 'Chic R2 Mtl Rose Gold', 'شيك R2 معدني روز غولد', 'Arabesque tile with a rose gold metallic finish. 20x20 cm.', 'Carreau arabesque avec finition métallique rose gold. 20x20 cm.', 'بلاط أرابيسك بتشطيب معدني روز غولد. 20×20 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-CHI-012.jpg'] FROM categories c WHERE c.slug = 'chic';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'chic-r2-mtl-silver', 'Chic R2 Mtl Silver', 'Chic R2 Mtl Silver', 'شيك R2 معدني فضي', 'Arabesque tile with an elegant silver metallic finish. 20x20 cm.', 'Carreau arabesque avec finition métallique argent. 20x20 cm.', 'بلاط أرابيسك بتشطيب معدني فضي أنيق. 20×20 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-CHI-013.jpg'] FROM categories c WHERE c.slug = 'chic';
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'chic-r2-mtl-bleu-petrole', 'Chic R2 Mtl Bleu Pétrole', 'Chic R2 Mtl Bleu Pétrole', 'شيك R2 معدني أزرق بترولي', 'Arabesque tile with a teal petroleum-blue metallic finish. 20x20 cm.', 'Carreau arabesque avec finition métallique bleu pétrole. 20x20 cm.', 'بلاط أرابيسك بتشطيب معدني أزرق بترولي. 20×20 سم.', 0.00, true, false, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-CHI-014.jpg'] FROM categories c WHERE c.slug = 'chic';

-- KRONFEL
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'kronfel', 'Kronfel', 'Kronfel', 'كرونفل', 'Traditional hand-painted square tile (20x20 cm) with rich blue, gold and red ornamental patterns.', 'Carreau carré peint à la main (20x20 cm) avec riches motifs ornementaux bleus, dorés et rouges.', 'بلاط مربع مطلي يدويًا (20×20 سم) بزخارف زهرية تقليدية غنية باللون الأزرق والذهبي والأحمر.', 0.00, true, true, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-KRO-001.jpg'] FROM categories c WHERE c.slug = 'kronfel';

-- CASBAH
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'casbah', 'Casbah', 'Casbah', 'قصبة', 'Andalusian-style hand-painted tile (20x20 cm) with vibrant blue, green and yellow botanical motifs.', 'Carreau peint à la main de style andalou (20x20 cm) avec motifs botaniques vibrants.', 'بلاط بالأسلوب الأندلسي مرسوم يدويًا (20×20 سم) بزخارف نباتية زاهية.', 0.00, true, true, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-CAS-001.jpg'] FROM categories c WHERE c.slug = 'casbah';

-- YASMINE
INSERT INTO products (category_id, slug, name_en, name_fr, name_ar, description_en, description_fr, description_ar, base_price, is_active, is_featured, images) SELECT c.id, 'yasmine', 'Yasmine', 'Yasmine', 'ياسمين', 'Ottoman-inspired hand-painted tile (20x20 cm) with intricate scrollwork and floral arabesque.', 'Carreau peint à la main d''inspiration ottomane (20x20 cm) avec arabesque florale et entrelacs.', 'بلاط مستوحى من العثمانية مرسوم يدويًا (20×20 سم) بزخارف تدوير وأرابيسك زهري.', 0.00, true, true, ARRAY['https://cffrahhkwvvlvdkpivxc.supabase.co/storage/v1/object/public/product-images/products/ARC-YAS-001.jpg'] FROM categories c WHERE c.slug = 'yasmine';

-- ── 4. VARIANTS (one Standard variant per product) ────────────
INSERT INTO product_variants (product_id, name_en, name_fr, name_ar, sku, price_modifier, stock)
SELECT
  p.id,
  'Standard',
  'Standard',
  'قياسي',
  upper(replace(p.slug, '-', '_')) || '_STD',
  0.00,
  100
FROM products p;

-- ── 5. VERIFY ────────────────────────────────────────────────
SELECT COUNT(*) AS total_products FROM products;
-- Expected: 57

SELECT COUNT(*) AS total_categories FROM categories;
-- Expected: 9

SELECT slug, images[1] AS image_url FROM products LIMIT 5;
-- Expected: full https:// URLs
